### PR TITLE
Feature add contributing update docs

### PR DESCRIPTION
**Pull request by stevepiercy**
See #13

### CODE REVIEW

**Comment by tseaver** [comment]
Probably should wait until PR #12 merges, and rebase to get Travis working.

**Comment by stevepiercy** [comment]
Sounds reasonable to me.

**Comment by stevepiercy** [comment]
Meh, the commit history is dirty after rebasing. I don't know how to fix that, other than redo the whole PR. Let me know if that matters and how to fix it.

**Comment by stevepiercy** [comment]
@tseaver ready for review

**Comment by tseaver** [comment]
@stevepiercy I used `git rebase -i` to clean up the commit history.  The net diff is unchanged.

**Comment by tseaver** [comment]
Note that what you needed was to merge your local `master` (not this branch, if rebasing), and *then* `git rebase master`.

**Comment by stevepiercy** [comment]
@tseaver thanks for mopping up after me.

**Pull request merged**
